#pragma config(Motor,  port2,           leftLift,      tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port3,           rightLift,     tmotorVex393_MC29, openLoop, reversed)
#pragma config(Motor,  port4,           rightWheel,    tmotorVex393_MC29, openLoop, reversed)
#pragma config(Motor,  port5,           leftWheel,     tmotorVex393_MC29, openLoop)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

task main()
{
	while (true) {
		motor[rightWheel] = vexRT[Ch2];
		motor[leftWheel] = vexRT[Ch3];
		if (((vexRT[Btn5U] && vexRT[Btn6U]) || vexRT[Btn8U]) && ! (vexRT[Btn8D])) {
			motor[leftLift] = 255;
			motor[rightLift] = 255;
		}
		else if ((vexRT[Btn5U] && vexRT[Btn6U]) || vexRT[Btn8D]) {
			motor[leftLift] = -255;
			motor[rightLift] = -255;
		}
		else if (vexRT[Btn5U]) {
			motor[leftLift] = 255;
			motor[rightLift] = 0;
		}
		else if (vexRT[Btn5D]) {
			motor[leftLift] = -255;
			motor[rightLift] = 0;
		}
		else if (vexRT[Btn6U]) {
			motor[rightLift] = 255;
			motor[leftLift] = 0;
		}
		else if (vexRT[Btn6D]) {
			motor[rightLift] = -255;
			motor[leftLift] = 0;
		}
		else {
			motor[leftLift] = 0;
			motor[rightLift] = 0;
		}
		//flip cap
		if (vexRT[Btn7U]) {
			motor[rightWheel] = 255;
			motor[leftWheel] = 255;
			motor[leftLift] = 255;
			motor[rightLift] = 255;
			delay (1300);
			motor[leftLift] = 0;
			motor[leftLift] = 0;
			motor[rightWheel] = 0;
			motor[leftWheel] = 0;
		}
		//climb on platform
		if (vexRT[Btn7L]) {
			motor[leftLift] = -255;
			motor[rightLift] = -255;
			delay (1000);
			motor[leftLift] = 0;
			motor[rightLift] = 0;
			motor[leftWheel] = 255;
			motor[rightWheel] = 255;
			delay (1200);
			motor[rightWheel] = 0;
			motor[leftWheel] = 0;
		}
		if (vexRT[Btn7D]) {
			motor[rightWheel] = 255;
			motor[leftWheel] = 255;
			delay (1000);
			motor[leftLift] = 255;
			motor[rightLift] = 255;
			delay (1300);
			motor[leftLift] = 0;
			motor[rightLift] = 0;
			motor[leftWheel] = -255;
			motor[rightWheel] = -255;
			delay(1000);
			motor[rightWheel] = 255;
			delay(1750);
			motor[rightWheel] = 255;
			motor[leftWheel] = 255;
			delay(1500);
			motor[leftWheel] = 0;
			motor[rightWheel] = 0;
			motor[leftLift] = -255;
			motor[rightLift] = -255;
			delay (1300);
			motor[leftLift] = 0;
			motor[rightLift] = 0;
			motor[leftWheel] = 255;
			motor[rightWheel] = 255;
			delay (1200);
			motor[rightWheel] = 0;
			motor[leftWheel] = 0;
		}
	}
}
